# Generated by Django 6.0.6 on 2026-06-30 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField()),
                ('motif', models.CharField(blank=True, default='Contrôle INR de routine', max_length=255)),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('honore', 'Honoré'), ('annule', 'Annulé'), ('absent', 'Patient absent')], default='planifie', max_length=10)),
                ('annule', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='patients.patient')),
            ],
            options={
                'ordering': ['date_heure'],
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_consultation', models.DateTimeField()),
                ('valeur_inr', models.DecimalField(decimal_places=2, help_text="Valeur mesurée de l'INR (ex : 2.40)", max_digits=4)),
                ('dose_comprimes', models.DecimalField(decimal_places=2, help_text='Nombre de comprimés de Sintrom 4 mg pris/prescrits par jour (ex : 0.5 = 1/2 cp)', max_digits=4)),
                ('dose_libre', models.CharField(blank=True, help_text='Texte libre si le schéma de dose est variable (ex : alternance 1/2-1 cp)', max_length=255)),
                ('saignement_signale', models.BooleanField(default=False, verbose_name='Saignement signalé par le patient')),
                ('observance_signalee', models.CharField(choices=[('bonne', 'Bonne observance'), ('partielle', 'Observance partielle'), ('mauvaise', 'Mauvaise observance / oublis')], default='bonne', max_length=20)),
                ('commentaire_medical', models.TextField(blank=True, help_text='Observations cliniques, ajustements envisagés, etc.')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='patients.patient')),
                ('rendez_vous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation', to='consultations.rendezvous')),
            ],
            options={
                'ordering': ['-date_consultation'],
            },
        ),
    ]
