# Generated by Django 6.0.6 on 2026-06-30 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='saignement_signale',
        ),
        migrations.AddField(
            model_name='consultation',
            name='evenement_hemorragique',
            field=models.BooleanField(default=False, verbose_name='Événement hémorragique survenu depuis la dernière consultation'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='evenement_thrombotique',
            field=models.BooleanField(default=False, verbose_name='Événement thrombotique/embolique survenu depuis la dernière consultation'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='types_evenements_hemorragiques',
            field=models.JSONField(blank=True, default=list, help_text='Sélection parmi la liste, si un événement hémorragique est signalé.', verbose_name="Type(s) d'événement hémorragique"),
        ),
        migrations.AddField(
            model_name='consultation',
            name='types_evenements_thrombotiques',
            field=models.JSONField(blank=True, default=list, help_text='Sélection parmi la liste, si un événement thrombotique/embolique est signalé.', verbose_name="Type(s) d'événement thrombotique/embolique"),
        ),
    ]
