# Generated by Django 6.0.6 on 2026-06-30 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_remove_consultation_saignement_signale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='motif_ajustement_dose',
            field=models.TextField(blank=True, help_text='Obligatoire si la dose change par rapport à la consultation précédente : justification médicale du changement décidé.', verbose_name="Motif de l'ajustement de dose"),
        ),
    ]
