# Generated by Django 6.0.6 on 2026-06-30 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('antecedents_medicaux', models.TextField(blank=True, help_text='HTA, diabète, cardiopathie, antécédents hémorragiques, etc.')),
                ('type_avc', models.CharField(choices=[('ischemique', 'AVC ischémique'), ('hemorragique', 'AVC hémorragique'), ('ait', 'Accident ischémique transitoire (AIT)'), ('non_avc', "Pas d'AVC — autre indication")], default='ischemique', max_length=20)),
                ('date_avc', models.DateField(blank=True, help_text="Date de l'AVC / événement initial", null=True)),
                ('molecule_avk', models.CharField(choices=[('acenocoumarol', 'Acénocoumarol (Sintrom 4 mg)'), ('warfarine', 'Warfarine'), ('fluindione', 'Fluindione (Préviscan)'), ('autre', 'Autre AVK')], default='acenocoumarol', max_length=20)),
                ('traitement_associe', models.TextField(blank=True, help_text='Autres traitements en cours (antihypertenseurs, statines, etc.)')),
                ('valve_mecanique', models.BooleanField(default=False, help_text='Modifie la cible INR recommandée (zone généralement plus haute).', verbose_name="Porteur d'une valve cardiaque mécanique")),
                ('type_valve', models.CharField(blank=True, help_text='Précision sur le type/position de la valve, si applicable.', max_length=255)),
                ('inr_cible_min', models.DecimalField(decimal_places=1, default=2.0, help_text='Borne basse de la cible INR pour ce patient (modifiable par le médecin).', max_digits=3)),
                ('inr_cible_max', models.DecimalField(decimal_places=1, default=3.0, help_text='Borne haute de la cible INR pour ce patient (modifiable par le médecin).', max_digits=3)),
                ('frequence_suivi', models.CharField(choices=[('15j', 'Tous les 15 jours'), ('1m', 'Tous les mois'), ('autre', 'Autre / à définir')], default='1m', max_length=10)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nom', 'prenom'],
            },
        ),
    ]
