# Generated by Django 6.0.6 on 2026-06-30 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='date_avc',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='type_avc',
        ),
        migrations.AddField(
            model_name='patient',
            name='creatinine',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Créatinine (mg/L)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='date_bilan_biologique',
            field=models.DateField(blank=True, null=True, verbose_name='Date du bilan biologique'),
        ),
        migrations.AddField(
            model_name='patient',
            name='date_evenement',
            field=models.DateField(blank=True, help_text="Date de l'événement médical initial (AVC, embolie, thrombose, pose de prothèse, etc.)", null=True, verbose_name="Date de l'événement"),
        ),
        migrations.AddField(
            model_name='patient',
            name='hemoglobine',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Hémoglobine (g/dL)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='indication',
            field=models.CharField(choices=[('avc_ischemique', 'AVC ischémique'), ('avc_hemorragique', 'AVC hémorragique (séquellaire)'), ('ait', 'Accident ischémique transitoire (AIT)'), ('fibrillation_atriale', 'Fibrillation atriale'), ('embolie_pulmonaire', 'Embolie pulmonaire'), ('thrombose_veineuse', 'Thrombose veineuse (profonde)'), ('prothese_mecanique_aortique', 'Prothèse mécanique aortique'), ('prothese_mecanique_mitrale', 'Prothèse mécanique mitrale'), ('autre', 'Autre indication')], default='fibrillation_atriale', max_length=30, verbose_name='Indication du traitement AVK'),
        ),
        migrations.AddField(
            model_name='patient',
            name='inr_biologie',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valeur de référence issue du bilan biologique global, distincte du suivi de consultation.', max_digits=4, null=True, verbose_name='INR (dernier bilan biologique)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='ionogramme',
            field=models.CharField(blank=True, help_text='ex : Na+ 138 mmol/L, K+ 4.2 mmol/L', max_length=255, verbose_name='Ionogramme sanguin'),
        ),
        migrations.AddField(
            model_name='patient',
            name='plaquettes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Plaquettes (/mm³)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='tp',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='TP — taux de prothrombine (%)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='uree',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Urée (g/L)'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='type_valve',
            field=models.CharField(blank=True, help_text='Type/modèle de la prothèse, si applicable.', max_length=255, verbose_name='Précision sur la prothèse'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='valve_mecanique',
            field=models.BooleanField(default=False, help_text="Renseigné automatiquement selon l'indication ; modifie la cible INR et la sensibilité des alertes de sous-dosage.", verbose_name="Porteur d'une prothèse cardiaque mécanique"),
        ),
    ]
